# Enables multi-finger gesture
# Place this file in ~/.config/fusuma/
# Run 'sudo fusuma' at startup

swipe:
  3:
    left:
      command: 'xdotool key super+q'
    right:
      command: 'xdotool key super+w'
    up:
      command: 'xdotool key super+s'
    down:
      command: 'xdotool key Escape'
  4:
    left:
      command: 'xdotool key super+q'
    right:
      command: 'xdotool key super+w'
    up:
      command: 'xdotool key super+s'
    down:
      command: 'xdotool key Escape'
pinch:
  in:
    command: 'xdotool key super'
  out:
     command: 'xdotool key super'

threshold:
  swipe: 0.2
  pinch: 0.4

interval:
  swipe: 0.2
  pinch: 0.1
